MyBlog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('topic_<int:topic_id>/', views.My_topic, name="My_topic"),
    path('<int:content_id>/', views.content_blog, name="content_blog"),
    path('<int:content_id>/add_likes', views.AddLikes, name="Add_Like"),
    path('<int:content_id>/del_likes', views.DisLike, name="Dis_Like"),
    path('', views.Blog, name="Blog"),
]

SergeiPlakunov/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('Blog/', include('MyBlog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('travel', views.travel, name="travel"),
    path('about_me', views.about_me, name="about_me"),
    path('meditation', views.meditation, name="meditation"),
    path('seo', views.seo, name="seo"),
    path('massag', views.massag, name="massag"),
]

MyBlog/models.py
from django.db import models

class Post(models.Model):
    """Основная структура поста"""
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    content = models.CharField(max_length=300, verbose_name="Краткое описание")
    content_big = models.TextField(null=True, blank=True, verbose_name="Описание")
    topic = models.ForeignKey('TopicPost', null=True, on_delete=models.PROTECT, verbose_name="Тема")
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Опубликовано")
    image = models.ImageField(upload_to='image/%Y', verbose_name="Изображение на зоголовок")


    class Meta:
        verbose_name_plural = "Посты"
        verbose_name = "Пост"
        ordering = ['-published']


class Photo_post(models.Model):
    """Фотографии для конкретного поста"""
    images = models.ImageField(upload_to='image/post/%Y', verbose_name="Изображение для поста")
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE, verbose_name="Пост")

    class Meta:
        verbose_name_plural = "Изоброжения для поста"
        verbose_name = "Изоброжения"
        ordering = ['post']


class TopicPost(models.Model):
    """Тема публикаций"""
    name = models.CharField(max_length=50, db_index=True, verbose_name="Название")

    def __str__(self):
       return self.name

    class Meta:
        verbose_name_plural = "Темы"
        verbose_name = "Тема"
        ordering = ['-id']

class Likes(models.Model):
    """лайки"""
    ip = models.CharField(max_length=100, verbose_name="ip-адрес")
    pos = models.ForeignKey(Post, verbose_name="Публикация", on_delete=models.CASCADE)

MyBlog/views.py
from django.shortcuts import render, redirect
from .models import Post, Likes
from .models import TopicPost
from .models import Photo_post



def Blog(request):
    MyBlog = Post.objects.all()
    topics = TopicPost.objects.all()
    return render(request, 'MyBlog/Blog.html', {"MyBlog": MyBlog, "topics": topics})


def My_topic(request, topic_id):
    MyPost = Post.objects.filter(topic=topic_id)
    Topics = TopicPost.objects.all()
    current_topic = TopicPost.objects.get(id=topic_id)
    context = {'MyPost': MyPost, 'Topics': Topics, 'current_topic': current_topic}
    return render(request, 'MyBlog/my_topic.html', context)


def content_blog(request, content_id):
    blog = Post.objects.get(id=content_id)
    image = Photo_post.objects.filter(post=content_id)
    return render(request, 'MyBlog/content_blog.html', {'blog': blog, 'image': image})

"""Получение ip адресса пользователя"""
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

"""Проверяем ip пользователя и добовляем запись"""
def AddLikes(request, content_id):
    ip_client = get_client_ip(request)
    try:
        Likes.objects.get(ip=ip_client, pos_id=content_id)
        return redirect(f'/Blog/{content_id}')
    except:
        new_like = Likes()
        new_like.ip = ip_client
        new_like.pos_id = int(content_id)
        new_like.save()
        return redirect(f'/Blog/{content_id}')

"""Проверяем ip пользователя и удаляем запись"""
def DisLike(request, content_id):
    ip_client = get_client_ip(request)
    try:
        Lik = Likes.objects.get(ip=ip_client)
        Lik.delete()
        return redirect(f'/Blog/{content_id}')
    except:
        return redirect(f'/Blog/{content_id}')

MyBlog/templates/MyBlog/Blog.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
    Мой блог
{% endblock %}

{% block content %}

    <!— Yandex.Metrika counter —>
<script type="text/javascript" >
(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
m[i].l=1*new Date();
for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

ym(93642517, "init", {
clickmap:true,
trackLinks:true,
accurateTrackBounce:true
});
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/93642517" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!— /Yandex.Metrika counter —>


    {% include "main/elements/Menu.html" %}
    {% block content_Blog %}
    <!--Заголовок страницы блога-->
    <div class="header_blog">
        <h1>Здравствуй, дорогой гость!</h1>
        <div class="p_inform">
            <p>Любишь путешествовать? Добро пожаловать в мою команду единомышленников!</p>
            <p>Блог - это моё пространство. Истории из жизни, поиск ответов на вопросы, путешествия, практики
                физического и духовного здоровья.</p>
            <p>Моя главная жизненная установка - человек хранитель жизни на Земле.</p>
            <p>У каждого из нас есть мечты, цели, желания, а вам хватает энергии для достижения желаемого? А где же
                черпать
                эту энергию? Как раскрыть наши ресурсы?</p>
            <p>Жизнь - это исследовательская лаборатория. Путешествия ее инструмент.</p>
            <p>Воссоединение с природой - путь к раскрытию и приумножению энергии жизни.</p>
            <p>Это мой вектор движения, присоединяйтесь! Я всегда открыт для вас.</p>
        </div>

        <h3>С уважением, Сергей Плакунов.</h3>
    </div>
    <!--Вывод постов-->
    <div class="posts">
            <div class="a_topic">
                <h1>Темы на выбор</h1>
                <a href="{% url "Blog" %}">Главная</a>
                {% for topic in topics %}
                    <a href="{% url "My_topic" topic.id %}">{{ topic.name }}</a>
                {% endfor %}
            </div>
            {% for Blog in MyBlog %}
                <div class="posts_info">
                    <img src="{{ Blog.image.url }}" alt="">
                    <div class="posts_info_text">
                        <a href="{% url "content_blog" Blog.id  %}"><h2>{{ Blog.title }}</h2></a>
                        <div class="data_publoshed"><i class="fa-solid fa-calendar-days"></i>{{ Blog.published }}
                            Тема: {{ Blog.topic }}</div>
                        <p>{{ Blog.content }}</p>
                        <a href="{% url "content_blog" Blog.id  %}">Продолжение...</a>
                    </div>
                </div>
            {% endfor %}

            </div>
        {% endblock %}
    <!--Блок подвал-->
    {% include "main/elements/footer.html" %}

{% endblock %}

MyBlog/templates/MyBlog/content_blog.html
{% extends 'MyBlog/Blog.html' %}
{% load static %}

{% block title %}
    Мой блог :: {{ blog.topic }}
{% endblock %}

{% block content_Blog %}
    <!— Yandex.Metrika counter —>
<script type="text/javascript" >
(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
m[i].l=1*new Date();
for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

ym(93642517, "init", {
clickmap:true,
trackLinks:true,
accurateTrackBounce:true
});
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/93642517" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!— /Yandex.Metrika counter —>



    <a href="{% url "Blog" %}" class="next_content_blog"><i class="fa-solid fa-circle-chevron-left"></i> Назад </a>
    <div class="content_block_Blog">
        <div class="header_content">
            <img src="{{ blog.image.url }}" alt="">
            <h2>{{ blog.title }}</h2>
            <p><i class="fa-solid fa-calendar-days"></i> {{ blog.published }}</p>
        </div>
        <div class="body_content">
            <p>{{ blog.content_big }}</p>
            <div class="geleri">
                {% for imga in image %}
                    <span class="image__wrapper">
                        <img src="{{ imga.images.url }}" alt="" class="minimized">
                    </span>
                {% endfor %}
            </div>

        </div>
    <div class="like_dislike">
        <a href="{% url "Add_Like" blog.id %}" class="like"><i class="fa-regular fa-thumbs-up"></i></a>
        <p>{{ blog.likes_set.all.count }}</p>
        <a href="{% url "Dis_Like" blog.id %}" class="dislike"><i class="fa-regular fa-thumbs-down"></i></a>
    </div>
    <div class="telegram_link">
        <h1>Для обсуждения переходите на мой Telegram канал, посвященный блогу, по ссылке <a href="https://t.me/+V55xjgX65stkZjEy" title="Telegram"><i class="fa-brands fa-telegram"></i></a></h1>
    </div>
    </div>
{% endblock %}

MyBlog/templates/MyBlog/my_topic.html
{% extends 'MyBlog/Blog.html' %}
{% load static %}

{% block title %}
    Мой блог :: {{ current_topic.name }}
{% endblock %}

{% block content_Blog %}
    <!— Yandex.Metrika counter —>
<script type="text/javascript" >
(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
m[i].l=1*new Date();
for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

ym(93642517, "init", {
clickmap:true,
trackLinks:true,
accurateTrackBounce:true
});
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/93642517" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!— /Yandex.Metrika counter —>


    <div class="posts">
        <div class="a_topic" style="margin: 100px 0 0 0;">
            <h1>Темы на выбор</h1>
            <a href="{% url "Blog" %}">Главная</a>
            {% for topic in Topics %}
                <a href="{% url "My_topic" topic.pk %}">{{ topic.name }}</a>
            {% endfor %}
        </div>
        <h1><span style="color: #9b9b9b">Тема:</span> {{ current_topic.name }}</h1>
        {% for Blog in MyPost %}
            <div class="posts_info">
                <img src="{{ Blog.image.url }}" alt="">
                <div class="posts_info_text">
                    <a href="{% url "content_blog" Blog.id  %}"><h2>{{ Blog.title }}</h2></a>
                    <div class="data_publoshed"><i class="fa-solid fa-calendar-days"></i>{{ Blog.published }}</div>
                    <p>{{ Blog.content }}</p>
                     <a href="{% url "content_blog" Blog.id  %}">Продолжение...</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}